# Generated by Django 5.2.10 on 2026-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='anonymous_name',
            field=models.CharField(default='Anonymous User', max_length=50),
            preserve_default=False,
        ),
    ]
