# Generated by Django 5.2.10 on 2026-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
    ]
